### ISSUE TITLE
Exam Feedback

### ISSUE THREAD

**Issue by s2t2** [gwu-business/istm-4121#31]
please use the space below for feedback about exams

**Comment by s2t2** [comment]
this single-issue forum would be better represented by individual issues as they arise.

**Comment by haton9** [comment]
Hi prof,
I spoke to you in class regarding the midterm grades and about the options that I could have regarding that. I know that you mentioned we have to choice to have the midterm percentage of our grades lowered to 15% and making the final worth 35%. I don't know if this is a smart way of doing it or not and i wanted your feedback regarding that. I also thought it would be a smarter way if you could add an extra assignment that could be counted towards our exam grades rather than putting all the weight towards the final exam.

**Comment by s2t2** [comment]
A handful of students are choosing to "wager" the max wager, 10% of the exam weight. This means their midterm exam will represent 40% of their total exam weight and their final will comprise 60% of their total exam weight. Let me know by last week's class (or even before the start of class tomorrow is fine, but please not any later) if you would like to like to exercise this option.
